package com.wakemethere.app.data.transit

import com.wakemethere.app.domain.model.TransitLine
import com.wakemethere.app.domain.model.TransitNetwork
import com.wakemethere.app.domain.model.TransitStation
import com.wakemethere.app.domain.model.TransitSystem
import org.json.JSONObject
import kotlin.math.asin
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt

/**
 * Parses the transit-network JSON (bundled assets or in-app updates).
 *
 * Schema v2 (generated by tools/build_transit_assets.py):
 * ```json
 * {
 *   "version": 2,
 *   "lines": [
 *     {
 *       "id": "1", "name": "خط ۱", "en": "Line 1", "color": "#E0001F",
 *       "stations": [ {"key": "Tajrish", "name": "تجریش", "en": "Tajrish",
 *                      "lat": 35.805, "lon": 51.433}, ... ],
 *       "edges": [[0, 1], [1, 2], ...]
 *     }
 *   ]
 * }
 * ```
 * Station "key"s are shared between lines, so a transfer station resolves to
 * one id ("<system>:<key>") across the whole network.
 *
 * Legacy v1 data (no "version"/"key"/"edges", e.g. old in-app updates) still
 * parses: ids fall back to "<system>:<lineId>:<index>" and edges are derived
 * from consecutive stations, skipping implausible >4 km jumps (bad data).
 */
object TransitParser {

    fun parse(system: TransitSystem, json: String): TransitNetwork {
        val root = JSONObject(json)
        val v2 = root.optInt("version", 1) >= 2
        val linesJson = root.getJSONArray("lines")
        val lines = buildList {
            for (i in 0 until linesJson.length()) {
                val lineJson = linesJson.getJSONObject(i)
                val lineId = lineJson.getString("id")
                val stationsJson = lineJson.getJSONArray("stations")
                val stations = buildList {
                    for (j in 0 until stationsJson.length()) {
                        val stationJson = stationsJson.getJSONObject(j)
                        val key = stationJson.optString("key")
                        add(
                            TransitStation(
                                id = if (v2 && key.isNotBlank()) {
                                    "${system.name}:$key"
                                } else {
                                    "${system.name}:$lineId:$j"
                                },
                                name = stationJson.getString("name"),
                                nameEn = stationJson.optString("en").takeIf { it.isNotBlank() },
                                latitude = stationJson.getDouble("lat"),
                                longitude = stationJson.getDouble("lon"),
                            )
                        )
                    }
                }
                add(
                    TransitLine(
                        id = lineId,
                        name = lineJson.getString("name"),
                        nameEn = lineJson.optString("en").takeIf { it.isNotBlank() },
                        color = parseColor(lineJson.getString("color")),
                        stations = stations,
                        edges = parseEdges(lineJson, stations),
                    )
                )
            }
        }
        return TransitNetwork(system = system, lines = lines)
    }

    private fun parseEdges(
        lineJson: JSONObject,
        stations: List<TransitStation>,
    ): List<Pair<Int, Int>> {
        val edgesJson = lineJson.optJSONArray("edges")
        if (edgesJson != null) {
            return buildList {
                for (e in 0 until edgesJson.length()) {
                    val pair = edgesJson.getJSONArray(e)
                    val a = pair.getInt(0)
                    val b = pair.getInt(1)
                    if (a in stations.indices && b in stations.indices && a != b) {
                        add(a to b)
                    }
                }
            }
        }
        // v1: consecutive stations are adjacent, unless implausibly far
        // apart (a straight line across half the city means broken data).
        return buildList {
            for (j in 1 until stations.size) {
                val d = distanceMeters(stations[j - 1], stations[j])
                if (d <= MAX_V1_EDGE_METERS) add(j - 1 to j)
            }
        }
    }

    /** Haversine distance in meters (pure Kotlin, JVM-testable). */
    fun distanceMeters(a: TransitStation, b: TransitStation): Double =
        distanceMeters(a.latitude, a.longitude, b.latitude, b.longitude)

    fun distanceMeters(lat1: Double, lon1: Double, lat2: Double, lon2: Double): Double {
        val la1 = Math.toRadians(lat1)
        val la2 = Math.toRadians(lat2)
        val dLa = Math.toRadians(lat2 - lat1)
        val dLo = Math.toRadians(lon2 - lon1)
        val h = sin(dLa / 2) * sin(dLa / 2) +
            cos(la1) * cos(la2) * sin(dLo / 2) * sin(dLo / 2)
        return 2 * EARTH_RADIUS_METERS * asin(sqrt(h))
    }

    /** Parses "#RRGGBB" into an opaque ARGB int without android.graphics. */
    private fun parseColor(hex: String): Int {
        val rgb = hex.removePrefix("#").toLong(16).toInt()
        return rgb or 0xFF000000.toInt()
    }

    private const val EARTH_RADIUS_METERS = 6_371_000.0
    private const val MAX_V1_EDGE_METERS = 4_000.0
}
