#!/usr/bin/env python3
"""Regenerates the bundled Tehran Metro / BRT station assets with exact
OpenStreetMap data via the Overpass API.

The app ships approximate coordinates (written without network access);
run this once on a machine with internet access to replace them:

    python3 tools/fetch_stations.py

It overwrites:
    app/src/main/assets/transit/tehran_metro.json
    app/src/main/assets/transit/tehran_brt.json

Requires: requests  (pip install requests)
"""

import json
import pathlib
import sys
import time

import requests

OVERPASS_URL = "https://overpass-api.de/api/interpreter"
ASSETS_DIR = pathlib.Path(__file__).resolve().parent.parent / "app/src/main/assets/transit"

# Official-ish line colors used by the map renderer.
METRO_COLORS = {
    "1": "#E0001B", "2": "#2F4389", "3": "#0098D8", "4": "#F9A825",
    "5": "#00A651", "6": "#E5097F", "7": "#7C2E8E",
}
BRT_COLOR_CYCLE = ["#C62828", "#EF6C00", "#2E7D32", "#4527A0", "#00838F",
                   "#6D4C41", "#455A64", "#AD1457", "#9E9D24", "#283593"]


def overpass(query: str) -> dict:
    response = requests.post(OVERPASS_URL, data={"data": query}, timeout=120,
                             headers={"User-Agent": "WakeMeThere/1.0 station refresh"})
    response.raise_for_status()
    return response.json()


def fetch_route_relations(route: str, network_regex: str) -> list:
    """Returns route relations (metro: route=subway, BRT: route=bus with BRT network)."""
    query = f"""
    [out:json][timeout:120];
    area["name:en"="Tehran"]["admin_level"~"6|7"]->.teh;
    relation["route"="{route}"]["network"~"{network_regex}",i](area.teh);
    out body;
    >;
    out skel qt;
    """
    return overpass(query)["elements"]


def build_lines(elements: list, colors: dict | None) -> list:
    nodes = {e["id"]: e for e in elements if e["type"] == "node"}
    lines = []
    for rel in (e for e in elements if e["type"] == "relation"):
        tags = rel.get("tags", {})
        ref = tags.get("ref") or tags.get("name", "?")
        stations, seen = [], set()
        for member in rel.get("members", []):
            if member["type"] != "node" or "stop" not in member.get("role", "stop"):
                continue
            node = nodes.get(member["ref"])
            if not node:
                continue
            name = node.get("tags", {}).get("name")
            if not name or name in seen:
                continue
            seen.add(name)
            stations.append({"name": name,
                             "lat": round(node["lat"], 5),
                             "lon": round(node["lon"], 5)})
        if len(stations) < 2:
            continue
        color = (colors or {}).get(ref) or BRT_COLOR_CYCLE[len(lines) % len(BRT_COLOR_CYCLE)]
        lines.append({"id": str(ref), "name": tags.get("name", f"Line {ref}"),
                      "color": color, "stations": stations})
    # One line per ref: keep the variant with the most stations.
    best = {}
    for line in lines:
        if line["id"] not in best or len(line["stations"]) > len(best[line["id"]]["stations"]):
            best[line["id"]] = line
    return sorted(best.values(), key=lambda l: l["id"])


def write_asset(file_name: str, lines: list) -> None:
    path = ASSETS_DIR / file_name
    payload = {"note": "Exact coordinates from OpenStreetMap (generated by tools/fetch_stations.py).",
               "lines": lines}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    total = sum(len(l["stations"]) for l in lines)
    print(f"wrote {path} ({len(lines)} lines, {total} stations)")


def main() -> int:
    print("Fetching Tehran Metro (route=subway)...")
    metro = build_lines(fetch_route_relations("subway", "metro|مترو"), METRO_COLORS)
    if metro:
        write_asset("tehran_metro.json", metro)
    time.sleep(5)  # be polite to Overpass

    print("Fetching Tehran BRT (route=bus, BRT network)...")
    brt = build_lines(fetch_route_relations("bus", "BRT|بی.?آر.?تی|تندرو"), None)
    if brt:
        write_asset("tehran_brt.json", brt)

    if not metro and not brt:
        print("Nothing fetched — check the Overpass queries.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
